return {
    defaults = {
        autoReload = false,
        fastReload = false,
        rapidFireDelay = 40,
    },
    features = {
        capabilities = {
            "silentAim",
            "triggerBot",
            "rapidFire",
            "rapidFireDelay",
            "autoReload",
            "fastReload",
            "headshotRate",
            "missRate",
            "boxes",
            "chams",
            "showEnemies",
            "showTeammates",
            "names",
            "health",
            "weapon",
        },
    },
    hydroxide = {
        "closure",
        "targeting",
    },
    id = "hoodrivals",
    initialState = {},
    label = "Hood Rivals",
    manifest = {
        gameIds = { 10648640958 },
        placeIds = { 77463332823746, 113272123504853 },
    },
    module = "games/hoodrivals/Adapter",
    presentation = "games/hoodrivals/Presentation",
    sources = {
        "games/hoodrivals/Adapter",
        "games/hoodrivals/Firearm",
        "games/hoodrivals/Presentation",
        "games/hoodrivals/Targeting",
        "games/hoodrivals/features/AutoReload",
        "games/hoodrivals/features/FastReload",
        "games/hoodrivals/features/RapidFire",
        "games/hoodrivals/features/SilentAim",
        "games/hoodrivals/features/TriggerBot",
    },
}
