return {
    defaults = {
        autoFight = false,
        autoMovement = false,
        botSkill = 85,
        combatStyle = "offensive",
        showWins = false,
        teleportBehind = false,
        noclip = false,
    },
    features = {
        capabilities = {
            "boxes",
            "chams",
            "chamsExcludeAccessories",
            "chamsPerPart",
            "showEnemies",
            "worldRenderer",
            "names",
            "health",
            "showWins",
            "autoFight",
            "autoMovement",
            "botSkill",
            "combatStyle",
            "teleportBehind",
            "noclip",
        },
        cosmetics = false,
    },
    hydroxide = { "targeting" },
    id = "duelinggrounds",
    initialState = {},
    label = "Dueling Grounds ⚔️",
    manifest = {
        gameIds = { 9051406594 },
        placeIds = { 94217045453265 },
    },
    module = "games/duelinggrounds/Adapter",
    presentation = "games/duelinggrounds/Presentation",
    sources = {
        "games/duelinggrounds/Adapter",
        "games/duelinggrounds/Presentation",
        "games/duelinggrounds/features/AutoMovement",
        "games/duelinggrounds/features/CombatPipeline",
        "games/duelinggrounds/features/CombatRuntime",
        "games/duelinggrounds/features/Noclip",
        "games/duelinggrounds/features/TeleportBehind",
        "games/duelinggrounds/features/WinTitles",
        "games/duelinggrounds/features/combat/Attacks",
        "games/duelinggrounds/features/combat/Combos",
        "games/duelinggrounds/features/combat/DefensiveStyle",
        "games/duelinggrounds/features/combat/DynamicStyle",
        "games/duelinggrounds/features/combat/EnemyPolicy",
        "games/duelinggrounds/features/combat/EnemyObserver",
        "games/duelinggrounds/features/combat/FlashyStyle",
        "games/duelinggrounds/features/combat/JumpAttackPolicy",
        "games/duelinggrounds/features/combat/OffensiveStyle",
        "games/duelinggrounds/features/combat/Skill",
        "games/duelinggrounds/features/combat/Styles",
        "games/duelinggrounds/features/combat/UltimatePolicy",
        "games/duelinggrounds/features/combat/defense/Planner",
        "games/duelinggrounds/features/combat/defense/Executor",
        "games/duelinggrounds/features/combat/offense/Executor",
        "games/duelinggrounds/recording/Persistence",
        "games/duelinggrounds/recording/Runtime",
        "games/duelinggrounds/recording/Sampler",
    },
}
