return {
    defaults = {
        autoFight = false,
        autoMovement = false,
        combatStyle = "offensive",
        teleportBehind = false,
        wallPhase = false,
    },
    features = {
        capabilities = {
            "boxes",
            "chams",
            "chamsExcludeAccessories",
            "chamsPerPart",
            "showEnemies",
            "worldRenderer",
            "names",
            "health",
            "autoFight",
            "autoMovement",
            "combatStyle",
            "teleportBehind",
            "wallPhase",
        },
        cosmetics = false,
    },
    hydroxide = { "targeting" },
    id = "duelinggrounds",
    initialState = {},
    label = "Dueling Grounds ⚔️",
    manifest = {
        gameIds = { 9051406594 },
        placeIds = { 94217045453265 },
    },
    module = "games/DuelingGrounds",
    presentation = "games/duelinggrounds/Presentation",
    sources = {
        "games/DuelingGrounds",
        "games/duelinggrounds/Presentation",
    },
}
