return {
    defaults = {
        antiHit = false,
        antiTrap = false,
        autoBlossom = false,
        autoFarm = false,
        autoFarmEternal = true,
        autoFarmIndex = false,
        autoFarmSecret = true,
        autoFarmServerHopping = true,
        autoOpenEggs = false,
        idleTreadmill = true,
        eggEsp = false,
        eggRadar = true,
        eggEspMinimumRarity = 1,
        eggEspMinimumSize = 0.5,
        hitAura = false,
        hitAuraIgnoreFriends = true,
        instantPrompts = false,
        lagSafeMovement = false,
        serverHop = false,
        serverHopAttempts = 0,
        serverHopMaxPing = 120,
        serverHopPingGuard = false,
        serverHopTargetPopulation = 6,
        trapEsp = false,
    },
    features = {
        capabilities = {
            "antiHit",
            "antiTrap",
            "autoBlossom",
            "autoFarm",
            "autoFarmEternal",
            "autoFarmIndex",
            "autoFarmSecret",
            "autoFarmServerHopping",
            "autoOpenEggs",
            "idleTreadmill",
            "eggEsp",
            "eggRadar",
            "eggEspMinimumRarity",
            "eggEspMinimumSize",
            "hitAura",
            "hitAuraIgnoreFriends",
            "instantPrompts",
            "lagSafeMovement",
            "serverHop",
            "serverHopMaxPing",
            "serverHopTargetPopulation",
            "trapEsp",
        },
        cosmetics = false,
    },
    hydroxide = {},
    id = "stealanegg",
    initialState = {},
    label = "Steal An Egg",
    manifest = {
        gameIds = { 10563114921 },
        placeIds = { 107778070777162 },
    },
    module = "games/stealanegg/Adapter",
    presentation = "games/stealanegg/Presentation",
    sources = {
        "games/stealanegg/Adapter",
        "games/stealanegg/Presentation",
        "games/stealanegg/features/AntiHit",
        "games/stealanegg/features/AntiTrap",
        "games/stealanegg/features/AutoBlossom",
        "games/stealanegg/features/AutoFarm",
        "games/stealanegg/features/AutoOpenEggs",
        "games/stealanegg/features/HighlightEsp",
        "games/stealanegg/features/HitAura",
        "games/stealanegg/features/InstantPrompts",
        "games/stealanegg/features/LagSafeMovement",
        "games/stealanegg/features/ServerHop",
        "games/stealanegg/features/WalkNavigator",
    },
}
