return {
    defaults = {
        aimSmoothness = 0,
        autoPickup = false,
        bhop = false,
        boxes = true,
        bombTimer = true,
        chams = true,
        fov = 180,
        fovCircle = true,
        fullScreenAim = false,
        gloveColorOverride = false,
        gloveOverride = false,
        headshotRate = 0,
        health = true,
        humanAim = false,
        knifeAura = false,
        maximumFov = 500,
        microStep = false,
        minimumFov = 40,
        missRate = 0,
        names = true,
        noFlash = false,
        noRecoil = false,
        noSmoke = false,
        noSpread = false,
        noWeaponSlow = false,
        rapidFire = false,
        alwaysScoped = false,
        shotAim = false,
        silentAim = false,
        skinOverrides = {},
        spinBot = false,
        triggerBot = false,
        utilityEsp = true,
        wallbang = false,
        weapon = true,
    },
    features = {
        capabilities = {
            "plotCopy",
        },
        cosmetics = false,
    },
    hydroxide = {},
    id = "town",
    initialState = {
        activeWeapon = nil,
        activeWeaponKind = nil,
        cosmeticWeapon = nil,
        cosmetics = {
            maximumWear = 1,
            minimumWear = 0,
            skin = "Stock",
            skinCount = 1,
            skinIndex = 1,
            statTrak = false,
            supportsStatTrak = false,
            wear = 0,
            weapon = nil,
        },
        cosmeticMode = "weapon",
        cosmeticsOpen = false,
        error = nil,
        menuVisible = true,
        observations = {},
        plotCopy = {
            active = false,
            confirmedProgress = 0,
            context = "",
            phase = "Ready",
            state = "idle",
        },
        bombObservation = {
            visible = false,
        },
        utilityObservations = {},
        gloves = {
            maximumWear = 1,
            minimumWear = 0,
            skin = "Game equipped",
            skinCount = 1,
            skinIndex = 0,
            wear = 0,
            weapon = "Gloves",
        },
    },
    label = "Town",
    manifest = {
        gameIds = { 1718755273 },
        placeIds = { 4991214437 },
    },
    module = "games/Town",
    sources = {
        "games/Town",
        "games/town/Canonical",
        "games/town/CheckpointStore",
        "games/town/CopyEngine",
        "games/town/CopyPlan",
        "games/town/ExecutionPlan",
    },
}
