return {
    composition = "games/counterblox/Composition",
    defaults = {},
    features = {
        capabilities = {
            "silentAim",
            "triggerBot",
            "wallbang",
            "knifeAura",
            "microStep",
            "spinBot",
            "bhop",
            "rapidFire",
            "bombTimer",
            "utilityEsp",
            "headshotRate",
            "missRate",
            "noSpread",
            "noRecoil",
            "noFlash",
            "noSmoke",
            "noWeaponSlow",
            "boxes",
            "chams",
            "names",
            "health",
            "weapon",
        },
    },
    hydroxide = {
        "targeting",
    },
    id = "counterblox",
    initialState = {},
    label = "Counterblox",
    manifest = {
        gameIds = { 7633926880 },
        placeIds = { 114234929420007 },
    },
    module = "games/Counterblox",
    presentation = "games/counterblox/Presentation",
    sources = {
        "games/Counterblox",
        "games/counterblox/Composition",
        "games/counterblox/Presentation",
    },
}
