return {
    defaults = {
        aimSmoothness = 0,
        autoPickup = false,
        bhop = false,
        boxes = true,
        bombTimer = true,
        chams = true,
        fov = 180,
        fovCircle = true,
        fullScreenAim = false,
        gloveColorOverride = false,
        gloveOverride = false,
        headshotRate = 0,
        health = true,
        humanAim = false,
        knifeAura = false,
        maximumFov = 500,
        microStep = false,
        minimumFov = 40,
        missRate = 0,
        names = true,
        noFlash = false,
        noRecoil = false,
        noSmoke = false,
        noSpread = false,
        noWeaponSlow = false,
        rapidFire = false,
        alwaysScoped = false,
        shotAim = false,
        silentAim = false,
        skinOverrides = {},
        spinBot = false,
        triggerBot = false,
        utilityEsp = true,
        wallbang = false,
        weapon = true,
    },
    features = {
        capabilities = {
            "silentAim",
            "triggerBot",
            "wallbang",
            "knifeAura",
            "microStep",
            "spinBot",
            "bhop",
            "rapidFire",
            "bombTimer",
            "utilityEsp",
            "headshotRate",
            "missRate",
            "noSpread",
            "noRecoil",
            "noFlash",
            "noSmoke",
            "noWeaponSlow",
            "boxes",
            "chams",
            "names",
            "health",
            "weapon",
        },
    },
    hydroxide = {
        "targeting",
    },
    id = "counterblox",
    initialState = {
        activeWeapon = nil,
        activeWeaponKind = nil,
        cosmeticWeapon = nil,
        cosmetics = {
            maximumWear = 1,
            minimumWear = 0,
            skin = "Stock",
            skinCount = 1,
            skinIndex = 1,
            statTrak = false,
            supportsStatTrak = false,
            wear = 0,
            weapon = nil,
        },
        cosmeticMode = "weapon",
        cosmeticsOpen = false,
        error = nil,
        menuVisible = true,
        observations = {},
        plotCopy = {
            active = false,
            confirmedProgress = 0,
            context = "",
            phase = "Ready",
            state = "idle",
        },
        bombObservation = {
            visible = false,
        },
        utilityObservations = {},
        gloves = {
            maximumWear = 1,
            minimumWear = 0,
            skin = "Game equipped",
            skinCount = 1,
            skinIndex = 0,
            wear = 0,
            weapon = "Gloves",
        },
    },
    label = "Counterblox",
    manifest = {
        gameIds = { 7633926880 },
        placeIds = { 114234929420007 },
    },
    module = "games/Counterblox",
    presentation = "games/counterblox/Presentation",
    sources = {
        "games/Counterblox",
        "games/counterblox/Presentation",
    },
}
