return {
    defaults = {
        fly = false,
        flySpeed = 60,
        meleeKnockback = false,
        meleeKnockbackForce = 120,
        speed = false,
        vehicleFly = false,
        vehicleFlySpeed = 100,
        walkSpeed = 32,
    },
    features = {
        capabilities = {
            "boxes",
            "chams",
            "showEnemies",
            "showTeammates",
            "names",
            "health",
            "weapon",
            "fly",
            "flySpeed",
            "meleeKnockback",
            "meleeKnockbackForce",
            "speed",
            "vehicleFly",
            "vehicleFlySpeed",
            "walkSpeed",
        },
        cosmetics = false,
    },
    hydroxide = {},
    id = "runaways",
    initialState = {},
    label = "RUNAWAYS",
    manifest = {
        gameIds = { 7585140258 },
        placeIds = { 118418618261207, 117311404196294 },
    },
    module = "games/runaways/Adapter",
    presentation = "games/runaways/Presentation",
    sources = {
        "games/runaways/Adapter",
        "games/runaways/Presentation",
        "games/runaways/Targeting",
        "games/runaways/features/Movement",
        "games/runaways/features/MeleeKnockback",
        "games/runaways/features/VehicleFly",
    },
}
