return {
    defaults = {
        aimSmoothness = 0,
        autoPickup = false,
        bhop = false,
        boxes = true,
        bombTimer = true,
        chams = true,
        fov = 180,
        fovCircle = true,
        fullScreenAim = false,
        gloveColorOverride = false,
        gloveOverride = false,
        headshotRate = 0,
        health = true,
        humanAim = false,
        knifeAura = false,
        maximumFov = 500,
        microStep = false,
        minimumFov = 40,
        missRate = 0,
        names = true,
        noFlash = false,
        noRecoil = false,
        noSmoke = false,
        noSpread = false,
        noWeaponSlow = false,
        rapidFire = false,
        alwaysScoped = false,
        shotAim = false,
        silentAim = false,
        skinOverrides = {},
        spinBot = false,
        triggerBot = false,
        utilityEsp = true,
        wallbang = false,
        weapon = true,
    },
    features = {
        capabilities = {
            "silentAim",
            "shotAim",
            "triggerBot",
            "autoPickup",
            "alwaysScoped",
            "humanAim",
            "bhop",
            "aimSmoothness",
            "headshotRate",
            "missRate",
            "boxes",
            "chams",
            "names",
            "health",
            "weapon",
            "utilityEsp",
            "noFlash",
            "noSmoke",
        },
        cosmetics = false,
        exclusiveOptions = {
            shotAim = { "silentAim", "humanAim" },
            silentAim = { "shotAim" },
        },
        optionLabels = {
            humanAim = "Human Aim",
            alwaysScoped = "Always Scoped",
            silentAim = "Camera Aim",
            shotAim = "Silent Aim",
        },
    },
    hydroxide = {
        "targeting",
    },
    id = "rivals",
    initialState = {
        activeWeapon = nil,
        activeWeaponKind = nil,
        cosmeticWeapon = nil,
        cosmetics = {
            maximumWear = 1,
            minimumWear = 0,
            skin = "Stock",
            skinCount = 1,
            skinIndex = 1,
            statTrak = false,
            supportsStatTrak = false,
            wear = 0,
            weapon = nil,
        },
        cosmeticMode = "weapon",
        cosmeticsOpen = false,
        error = nil,
        menuVisible = true,
        observations = {},
        plotCopy = {
            active = false,
            confirmedProgress = 0,
            context = "",
            phase = "Ready",
            state = "idle",
        },
        bombObservation = {
            visible = false,
        },
        utilityObservations = {},
        gloves = {
            maximumWear = 1,
            minimumWear = 0,
            skin = "Game equipped",
            skinCount = 1,
            skinIndex = 0,
            wear = 0,
            weapon = "Gloves",
        },
    },
    label = "RIVALS",
    manifest = {
        gameIds = { 6035872082 },
        placeIds = { 17625359962 },
    },
    module = "games/rivals/Adapter",
    sources = {
        "games/rivals/Adapter",
        "games/rivals/Targeting",
        "games/rivals/ProjectileAim",
        "games/rivals/ShotPresentation",
        "games/rivals/ScopedAccuracy",
        "games/rivals/WeaponPolicy",
        "games/rivals/Effects",
        "games/rivals/Movement",
        "games/rivals/CombatState",
    },
}
