return {
    defaults = {
        autoCounter = false,
        taskAutomationPaused = true,
        taskAutomationEmergencyKey = "End",
        infiniteJump = false,
        wallNoclip = false,
        wallPhase = false,
        teleportBehind = false,
    },
    features = {
        capabilities = {
            "silentAim",
            "shotAim",
            "triggerBot",
            "autoCounter",
            "autoPickup",
            "alwaysScoped",
            "humanAim",
            "bhop",
            "infiniteJump",
            "wallNoclip",
            "teleportBehind",
            "aimSmoothness",
            "headshotRate",
            "missRate",
            "boxes",
            "chams",
            "chamsExcludeAccessories",
            "chamsPerPart",
            "showEnemies",
            "showTeammates",
            "worldRenderer",
            "names",
            "health",
            "weapon",
            "utilityEsp",
            "noFlash",
            "noSmoke",
            "taskAutomationPaused",
            "taskAutomationEmergencyKey",
        },
        cosmetics = false,
        exclusiveOptions = {
            shotAim = { "silentAim", "humanAim" },
            silentAim = { "shotAim" },
        },
        optionLabels = {
            humanAim = "Human Aim",
            alwaysScoped = "Always Scoped",
            autoCounter = "Auto Counter",
            teleportBehind = "Warp",
            silentAim = "Camera Aim",
            shotAim = "Silent Aim",
            taskAutomationPaused = "Pause Task Farming",
            taskAutomationEmergencyKey = "Emergency Stop",
        },
    },
    hydroxide = {
        "targeting",
    },
    id = "rivals",
    initialState = {},
    label = "RIVALS",
    manifest = {
        gameIds = { 6035872082 },
        placeIds = { 17625359962 },
    },
    module = "games/rivals/Adapter",
    presentation = "games/rivals/Presentation",
    sources = {
        "games/rivals/Adapter",
        "games/rivals/Session",
        "games/rivals/Presentation",
        "games/rivals/features/CameraAim",
        "games/rivals/features/SilentAim",
        "games/rivals/features/ShotPresentation",
        "games/rivals/features/TeleportBehind",
        "games/rivals/features/TriggerBot",
        "games/rivals/features/AutoCounter",
        "games/rivals/features/NoScope",
        "games/rivals/features/Pickup",
        "games/rivals/features/ScopedAccuracy",
        "games/rivals/features/AutoCounterRuntime",
        "games/rivals/features/AutoCounterTestSimulator",
        "games/rivals/features/GunGameRuntime",
        "games/rivals/libraries/HookRuntime",
        "games/rivals/libraries/ItemPolicy",
        "games/rivals/libraries/ItemInput",
        "games/rivals/libraries/WeaponPolicy",
        "games/rivals/libraries/Targeting",
        "games/rivals/libraries/ProjectileAim",
        "games/rivals/libraries/CombatState",
        "games/rivals/libraries/ModePolicy",
        "games/rivals/libraries/Movement",
        "games/rivals/tasks/TaskPolicy",
        "games/rivals/tasks/TaskFarmRuntime",
        "games/rivals/tasks/PracticeTaskDriver",
        "games/rivals/tasks/TaskCamera",
        "games/rivals/tasks/TaskWeaponSwap",
        "games/rivals/tasks/TaskSkillRuntime",
        "games/rivals/tasks/TaskCounterPolicy",
        "games/rivals/tasks/TaskLoadout",
        "games/rivals/world/Effects",
        "games/rivals/world/UtilityPolicy",
        "games/rivals/world/VisualSuppression",
        "games/rivals/world/TrajectoryRenderer",
        "games/rivals/world/ObservationRuntime",
        "games/rivals/world/WorldPolicy",
    },
}
